//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANALIZA_ILOSCIOWA_ARTYKULOW_ZAM_V
    {
        public decimal id_artykulu { get; set; }
        public string nazwa { get; set; }
        public string jednostka { get; set; }
        public Nullable<decimal> stan { get; set; }
        public Nullable<decimal> ilosc_dostepna { get; set; }
        public Nullable<decimal> stan_min { get; set; }
        public Nullable<decimal> stan_max { get; set; }
        public Nullable<decimal> dostawcy_zamowili { get; set; }
        public Nullable<decimal> dostawcy_do_realizacji { get; set; }
        public Nullable<decimal> odbiorcy_zamowili { get; set; }
        public Nullable<decimal> odbiorcy_do_realizacji { get; set; }
        public Nullable<decimal> odbiorcy_zarezerwowano { get; set; }
        public Nullable<decimal> odbiorcy_do_rezerwacji { get; set; }
        public Nullable<decimal> id_magazynu { get; set; }
        public Nullable<decimal> id_kategorii { get; set; }
        public Nullable<decimal> id_jednostki { get; set; }
        public Nullable<decimal> stan_prognozowany { get; set; }
        public string indeks_katalogowy { get; set; }
        public string indeks_handlowy { get; set; }
        public string RODZAJ { get; set; }
        public string PKWiU { get; set; }
        public string SWWKU { get; set; }
        public Nullable<decimal> CENA_ZAKUPU_BRUTTO { get; set; }
        public Nullable<decimal> CENA_ZAKUPU_NETTO { get; set; }
        public string LOKALIZACJA { get; set; }
        public string NAZWA_CERTYFIKATU { get; set; }
        public Nullable<int> DATA_CERTYFIKATU { get; set; }
        public Nullable<int> PLU { get; set; }
        public Nullable<decimal> ID_CENY_DOM { get; set; }
        public Nullable<decimal> ID_JEDNOSTKI_ZAK { get; set; }
        public Nullable<decimal> ID_JEDNOSTKI_SPRZ { get; set; }
        public string VAT_ZAKUPU { get; set; }
        public string VAT_SPRZEDAZY { get; set; }
        public string NAZWA2 { get; set; }
        public Nullable<decimal> OD_DOSTAWCOW { get; set; }
        public Nullable<decimal> DO_ODBIORCOW { get; set; }
        public Nullable<byte> CERTYFIKAT { get; set; }
        public string kod_kreskowy { get; set; }
        public string nazwa_oryg { get; set; }
        public Nullable<byte> zablokowany { get; set; }
        public Nullable<decimal> id_kategorii_tree { get; set; }
        public Nullable<byte> marzowy { get; set; }
    }
}
