//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WAPRO_DEMO_Entities : DbContext
    {
        public WAPRO_DEMO_Entities()
            : base("name=WAPRO_DEMO_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANALIZA_ILOSCIOWA_ARTYKULOW_ZAM_V> ANALIZA_ILOSCIOWA_ARTYKULOW_ZAM_V { get; set; }
    }
}
