//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIDOK_ZAMOWIENIE
    {
        public decimal IdZamowienia { get; set; }
        public string Numer { get; set; }
        public Nullable<System.DateTime> DataWystawienia { get; set; }
        public Nullable<System.DateTime> DataRealizacji { get; set; }
        public string NumerZamowieniaKlienta { get; set; }
        public string Priorytet { get; set; }
        public Nullable<decimal> SumaZaliczek { get; set; }
        public Nullable<decimal> WartoscNetto { get; set; }
        public Nullable<decimal> WartoscBrutto { get; set; }
        public Nullable<decimal> WartoscVat { get; set; }
        public Nullable<decimal> WartoscNettoWal { get; set; }
        public Nullable<decimal> WartoscBruttoWal { get; set; }
        public Nullable<decimal> WartoscVatWal { get; set; }
        public Nullable<decimal> PrzelicznikWal { get; set; }
        public Nullable<System.DateTime> DataKursuWaluty { get; set; }
        public string SymbolWaluty { get; set; }
        public Nullable<byte> ZamowienieWalutowe { get; set; }
        public string TypZamowienia { get; set; }
        public string TrybRezerwacji { get; set; }
        public string Uwagi { get; set; }
        public Nullable<decimal> IdKontrahenta { get; set; }
        public decimal IdMagazynu { get; set; }
        public decimal IdFirmy { get; set; }
        public string StanZamowienia { get; set; }
        public string StanRealizacji { get; set; }
        public Nullable<decimal> IdPracownika { get; set; }
        public Nullable<byte> DokZablokowany { get; set; }
        public string Pole1 { get; set; }
        public string Pole2 { get; set; }
        public string Pole3 { get; set; }
        public string Pole4 { get; set; }
        public string Pole5 { get; set; }
        public string Pole6 { get; set; }
        public string Pole7 { get; set; }
        public string Pole8 { get; set; }
        public string Pole9 { get; set; }
        public string Pole10 { get; set; }
        public Nullable<byte> TrybRejestracji { get; set; }
        public Nullable<decimal> RabatNarzut { get; set; }
        public string FORMA_PLATNOSCI { get; set; }
        public Nullable<int> DNI_PLATNOSCI { get; set; }
        public Nullable<byte> FAKTURA_DO_ZAMOWIENIA { get; set; }
    }
}
